# Generated by Django 2.1.4 on 2018-12-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20181224_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dtae_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
