# Generated by Django 2.1.4 on 2018-12-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_dtae_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dtae_added',
            new_name='date_added',
        ),
    ]
