# Generated by Django 2.1.4 on 2018-12-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20181226_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_list',
            old_name='date',
            new_name='task_date',
        ),
        migrations.AlterField(
            model_name='task_date',
            name='date_added',
            field=models.DateField(unique=True),
        ),
    ]
